PAD_ID = 0
UNK_ID = 1
START_ID = 2
EOS_ID = 3
DATA_DIR = "./data/"
max_w = 50
float_size = 4
special_words = ['<PAD>', '<UNK>', '<GO>',  '<EOS>']
special_words_id = [PAD_ID, UNK_ID, START_ID,  EOS_ID]
MODEL_DIR="./models"
MODEL_FILE="xiaohuangji"
MAX_TRAIN_SAMPLE_NUM = 100
batch_size=256
MAX_SEQUENCE = 12
EPOCH = 500
num_checkpoints=5
vocabulary_sw = 0
word_index_file="word_index_xiao"
index_word_file="word_index_xiao"
corpus_file="xiaohuangji.txt"
rnn_dim = 256
layer_num = 1
